### ISSUE TITLE
Gun turrets are killing me!

### ISSUE THREAD

**Issue by RMuskovets** [Bilka2/Ruins#10]
There's a problem with gun turrets being on 'neutral' force and thus killing every single player or enemy... I guess I should turn friendly fire off but I think that should be either in README or what's kind of better, included in the mod.

**Comment by Bilka2** [comment]
This okay?
![image](https://user-images.githubusercontent.com/27060268/83129337-f3b20180-a0dc-11ea-96be-c8980663b35e.png)

**Comment by RMuskovets** [comment]
Oh.. I thought I read the entire description... Anyway, thanks and sorry!
